apiVersion: enmasse.io/v1beta1
kind: Address
metadata:
  name: production.prodqueue #addressspace.addressname
spec:
  address: prodqueue
  type: queue
  plan: queue # address plan: queue and topic are available
