apiVersion: enmasse.io/v1beta1
kind: Address
metadata:
  name: eng.myqueue #addressspace.addressname
spec:
  address: myqueue
  type: queue
  plan: queue # address plan: queue and topic are available
