apiVersion: enmasse.io/v1beta1
kind: AddressSpace
metadata:
  name: team3-space
spec:
  type: standard
  plan: standard-input # address space plan
  authenticationService:
    name: standard-authservice
  endpoints:
    - name: messaging
      service: messaging
      expose:
        type: route
        routeHost: messaging-test.apps.amqhackfest-emea03.openshift.opentlc.com
        routeTlsTermination: passthrough
        routeServicePort: amqps
      cert:
        provider: openshift
        # tlsKey: ZXhhbXBsZSAtbgo=
        # tlsCert: ZXhhbXBsZSAtbgo=
      export:
        - kind: ConfigMap
          name: myconfig
        - kind: Service
          name: myservice
    - name: console
      service: console
      expose:
        type: route
        routeTlsTermination: reencrypt
        routeServicePort: https
      cert:
        provider: openshift