apiVersion: admin.enmasse.io/v1beta2
kind: AddressSpacePlan
metadata:
  name: standard-input
  labels:
    app: enmasse
spec:
  displayName: Medium
  displayOrder: 0
  infraConfigRef: team3-default
  addressSpaceType: standard
  resourceLimits:
    router: 3.0
    broker: 3.0
    aggregate: 6.0
  addressPlans:
  - alerts-multicast
  - results-queue
  - input-online-queue
  - input-batch-queue
